#!/usr/bin/env python

import os, sys
from subprocess import CalledProcessError, call
from subprocess_tee import run

def mvntee():
    args = sys.argv[1:]
    if (len(args) < 2):
        print("Usage prbuild.py <logPath> <stepOutputPath> <cmd> ...")
        return 99
    logpath = args[0]
    outpath = args[1]
    try:
        run(args[2:], check=True, echo=True)
    except CalledProcessError as ex:
        with open(logpath, 'w') as ansi:
            ansi.write(ex.stdout)
        htmlpath = logpath + ".html"
        call(f"ansi2html --no-wrap < {logpath} > {htmlpath}", shell=True)
        htmlpath = os.path.abspath(htmlpath)
        with open(outpath, 'a') as out:
            out.write(f"loghtml={htmlpath}\n")
        return ex.returncode
    return 0

if __name__ == '__main__':
    sys.exit(mvntee())
