name: Notify

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: felfert/action-send-mail@fix-envelope
        with:
          server_address: ${{secrets.SMTP_SERVER}}
          ignore_cert: false
          username: ${{secrets.SMTP_USER}}
          password: ${{secrets.SMTP_PASSWORD}}
          from: 'Jclouds PR <noreply@fritz-elfert.de>'
          to: jclouds@fritz-elfert.de,
          subject: "Test notification"
          body: "Plain body"
          envelope_from: noreply@github.com
          nodemailerdebug: true
