name: Notify

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: felfert/action-send-mail@fix-234
        with:
          server_address: ${{secrets.SMTP_SERVER}}
          server_port: 587
          ignore_cert: false
          username: ${{secrets.SMTP_USER}}
          password: ${{secrets.SMTP_PASSWORD}}
          from: 'Jclouds PR <noreply@github.com>'
          to: me@fritz-elfert.de
          subject: "Test notification"
          body: "Plain body"
          envelope_to: 'Fritz Elfert <me@fritz-elfert.de>, Someone Else <whonows@fritz-elfert.de>'
          nodemailerdebug: true
