name: Notify

on:
  workflow_dispatch:
    inputs:
      from:
        required: false
      envelopefrom:
        required: false
      envelopeto:
        required: false

jobs:
  notify1:
    runs-on: ubuntu-latest
    steps:
      - name: with
        uses: felfert/action-send-mail@relax-from-check
        with:
          server_address: ${{secrets.SMTP_SERVER}}
          server_port: 587
          ignore_cert: false
          username: ${{secrets.SMTP_USER}}
          password: ${{secrets.SMTP_PASSWORD}}
          from: ${{ github.event.inputs.from }}
          to: me@fritz-elfert.de
          subject: "Test notification"
          body: "Plain body"
          envelope_from: ${{ github.event.inputs.envelopefrom }}
          envelope_to: ${{ github.event.inputs.envelopeto }}
          nodemailerdebug: true
